Participant tickets
ijlik/ticket-app pull request #15
Opened 2024-11-07 06:02 UTC by Dayat281296

2024-11-07 11:31 UTC, ijlik commented
Untuk ini ada kesalahan dari awal mas @Dayat281296 

harusnya di awal checkout ke main dulu, kemudian dilakukan git pull origin main. baru kemudian buat branch participant ticket

kalau seperti ini perubahanya terlalu banyak ada 249 file changes

2024-11-07 11:32 UTC, ijlik requested changes
perlu perbaikan dari awal

2024-11-07 11:34 UTC, Dayat281296 commented
Baik nanti saya coba kembali. Maksud dari yang mas adi jelaskan🙏🏻🙏🏻🙏🏻
Kam, 7 Nov 2024 pukul 18.32 Adi Nugroho ***@***.***> menulis:

> ***@***.**** requested changes on this pull request.
>
> perlu perbaikan dari awal
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ijlik/ticket-app/pull/15#pullrequestreview-2420712149>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BMWLE25W5JADD4PS22ZA25DZ7NFVLAVCNFSM6AAAAABRKNIWVOVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDIMRQG4YTEMJUHE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-11-07 11:35 UTC, Dayat281296 commented
Mungkin bisa bantu jelaskan step by stepnya mas🙏🏻

Kam, 7 Nov 2024 pukul 18.34 Saga Samut ***@***.***> menulis:

> Baik nanti saya coba kembali. Maksud dari yang mas adi jelaskan🙏🏻🙏🏻🙏🏻
>
> Kam, 7 Nov 2024 pukul 18.32 Adi Nugroho ***@***.***>
> menulis:
>
>> ***@***.**** requested changes on this pull request.
>>
>> perlu perbaikan dari awal
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/ijlik/ticket-app/pull/15#pullrequestreview-2420712149>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/BMWLE25W5JADD4PS22ZA25DZ7NFVLAVCNFSM6AAAAABRKNIWVOVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDIMRQG4YTEMJUHE>
>> .
>> You are receiving this because you were mentioned.Message ID:
>> ***@***.***>
>>
>

2024-11-07 11:36 UTC, ijlik commented
1. git checkout main
2. git pull origin main
3. buat branch baru -> git branch {nama_branch}
4. git checkout {nama_branch}
5. proses pengerjaan di local
6. simpan perubahan -> git add .
7. git commit -m "message"
8. git push origin {nama_branch}
9. buat pull request dari {nama_branch} ke main

2024-11-07 11:42 UTC, Dayat281296 commented
Saya ulang dari awal aja kali mas ya

Kam, 7 Nov 2024 pukul 18.37 Adi Nugroho ***@***.***> menulis:

>
>    1. git checkout main
>    2. git pull origin main
>    3. buat branch baru -> git branch {nama_branch}
>    4. git checkout {nama_branch}
>    5. proses pengerjaan di local
>    6. simpan perubahan -> git add .
>    7. git commit -m "message"
>    8. git push origin {nama_branch}
>    9. buat pull request dari {nama_branch} ke main
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ijlik/ticket-app/pull/15#issuecomment-2462011316>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BMWLE272RNSH4IFYPNHTTODZ7NGGJAVCNFSM6AAAAABRKNIWVOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDINRSGAYTCMZRGY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-11-07 11:47 UTC, ijlik commented
iya pak

2024-11-07 11:57 UTC, closed without merging

2024-11-07 12:02 UTC, Dayat281296 commented
muncul error ini mas
PS C:\pelatihan\ticket-app> git checkout main
error: Your local changes to the following files would be overwritten by
checkout:
        resources/views/dashboard-layouts/dashboard.blade.php
        resources/views/participant.blade.php
        routes/web.php
Please commit your changes or stash them before you switch branches.
Aborting

Pada Kam, 7 Nov 2024 pukul 18.47 Adi Nugroho ***@***.***>
menulis:

> iya pak
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ijlik/ticket-app/pull/15#issuecomment-2462030242>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BMWLE222T4RMUH6LD5ZKIULZ7NHMVAVCNFSM6AAAAABRKNIWVOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDINRSGAZTAMRUGI>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-11-10 03:30 UTC, Dayat281296 commented
*Warning*: Unknown: Failed to open stream: No such file or directory in
*Unknown* on line *0*

*Fatal error*: Failed opening required
'C:\pelatihan\ticket-app\vendor\laravel\framework\src\Illuminate\Foundation\Console/../resources/server.php'
(include_path='.;C:/laragon/etc/php/pear') in *Unknown* on line
*0*

mau tanya error ini mas.


Pada Kam, 7 Nov 2024 pukul 19.23 Saga Samut ***@***.***> menulis:

> sudah mas bisa samean cek nggeh
>
>
> Pada Kam, 7 Nov 2024 pukul 19.01 Saga Samut ***@***.***> menulis:
>
>> muncul error ini mas
>> PS C:\pelatihan\ticket-app> git checkout main
>> error: Your local changes to the following files would be overwritten by
>> checkout:
>>         resources/views/dashboard-layouts/dashboard.blade.php
>>         resources/views/participant.blade.php
>>         routes/web.php
>> Please commit your changes or stash them before you switch branches.
>> Aborting
>>
>> Pada Kam, 7 Nov 2024 pukul 18.47 Adi Nugroho ***@***.***>
>> menulis:
>>
>>> iya pak
>>>
>>> —
>>> Reply to this email directly, view it on GitHub
>>> <https://github.com/ijlik/ticket-app/pull/15#issuecomment-2462030242>,
>>> or unsubscribe
>>> <https://github.com/notifications/unsubscribe-auth/BMWLE222T4RMUH6LD5ZKIULZ7NHMVAVCNFSM6AAAAABRKNIWVOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDINRSGAZTAMRUGI>
>>> .
>>> You are receiving this because you were mentioned.Message ID:
>>> ***@***.***>
>>>
>>