model dan migration participants_ticket sementara
ijlik/ticket-app pull request #40
Opened 2024-11-20 03:23 UTC by Dayat281296

2024-11-20 03:30 UTC, KangFarouq1745 requested changes

2024-11-20 03:30 UTC, KangFarouq1745 commented on app/Http/Controllers/ParticipantsTicketController.php
> +        $request->validate([
validasi harus dibuat file terpisah.

2024-11-20 03:30 UTC, KangFarouq1745 commented on app/Http/Controllers/ParticipantsTicketController.php
> +        $request->validate([
validasi harus dibuat file terpisah

2024-11-21 07:37 UTC, ijlik approved these changes

2024-11-21 07:37 UTC, merged